import type { NextPage } from "next";
import Head from "next/head";
import fetchLeaderboard, { Player } from "../async/fetchLeaderboard";

const Leaderboard: NextPage<{ data: Array<Player> }> = ({ data }) => {
  return (
    <div>
      <Head>
        <title>Six Mans - Leaderboard | UNCC Rocket League Esports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ul>
          {data.map((player) => (
            <li>
              <p>{player.name}</p>
              <p>{player.mmr}</p>
              <p>{player.wins}</p>
              <p>{player.losses}</p>
              <p>{player.matchesPlayed}</p>
              <p>{player.winPerc}</p>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  const data = await fetchLeaderboard();

  return {
    props: data
  };
}

export default Leaderboard;
