import type { NextPage } from "next";
import Head from "next/head";
import fetchWinners, { Season } from "../async/fetchWinners";

const Winners: NextPage<{ data: Array<Season> }> = ({ data }) => {
  return (
    <div>
      <Head>
        <title>Six Mans - Winners | UNCC Rocket League Esports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {data.map(({ seasonEnded, semester, winners }) => (
          <div>
            <p>{seasonEnded}</p>
            <p>{semester}</p>
            <ul>
              {winners.map((winner) => (
                <li>
                  <p>{winner.title}</p>
                  <p>{winner.name}</p>
                  {winner.mmr ? <p>{winner.mmr}</p> : null}
                  <p>{winner.wins}</p>
                  <p>{winner.losses}</p>
                  <p>{winner.matchesPlayed}</p>
                  <p>{winner.winPerc}</p>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const data = await fetchWinners();

  return {
    props: data,
    revalidate: 10,
  };
}

export default Winners;
